//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSqlAzMan.SnapIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetSqlAzMan.SnapIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Allow {
            get {
                object obj = ResourceManager.GetObject("Allow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AllowForDelegation {
            get {
                object obj = ResourceManager.GetObject("AllowForDelegation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Application_16x16 {
            get {
                object obj = ResourceManager.GetObject("Application_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Application_32x32 {
            get {
                object obj = ResourceManager.GetObject("Application_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon AuthorizationAttribute_16x16 {
            get {
                object obj = ResourceManager.GetObject("AuthorizationAttribute_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AuthorizationAttribute_32x32 {
            get {
                object obj = ResourceManager.GetObject("AuthorizationAttribute_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BizRule {
            get {
                object obj = ResourceManager.GetObject("BizRule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon DBUser_16x16 {
            get {
                object obj = ResourceManager.GetObject("DBUser_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DBUser_32x32 {
            get {
                object obj = ResourceManager.GetObject("DBUser_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Deny {
            get {
                object obj = ResourceManager.GetObject("Deny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FILECOPY_16 {
            get {
                object obj = ResourceManager.GetObject("FILECOPY_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Folder_16x16 {
            get {
                object obj = ResourceManager.GetObject("Folder_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Folder_32x32 {
            get {
                object obj = ResourceManager.GetObject("Folder_32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Hierarchy_16x16 {
            get {
                object obj = ResourceManager.GetObject("Hierarchy_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hierarchy_32x32 {
            get {
                object obj = ResourceManager.GetObject("Hierarchy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ItemAuthorization_16x16 {
            get {
                object obj = ResourceManager.GetObject("ItemAuthorization_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemAuthorization_32x32 {
            get {
                object obj = ResourceManager.GetObject("ItemAuthorization_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ItemAuthorization_32x321 {
            get {
                object obj = ResourceManager.GetObject("ItemAuthorization_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon NetSqlAzMan_16x16 {
            get {
                object obj = ResourceManager.GetObject("NetSqlAzMan_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon NetSqlAzMan_32x32 {
            get {
                object obj = ResourceManager.GetObject("NetSqlAzMan_32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Neutral {
            get {
                object obj = ResourceManager.GetObject("Neutral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Operation_16x16 {
            get {
                object obj = ResourceManager.GetObject("Operation_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Operation_32x32 {
            get {
                object obj = ResourceManager.GetObject("Operation_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Options_16x16 {
            get {
                object obj = ResourceManager.GetObject("Options_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options_32x32 {
            get {
                object obj = ResourceManager.GetObject("Options_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Role_16x16 {
            get {
                object obj = ResourceManager.GetObject("Role_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Role_32x32 {
            get {
                object obj = ResourceManager.GetObject("Role_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon SIDNotFound_16x16 {
            get {
                object obj = ResourceManager.GetObject("SIDNotFound_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon SIDNotFound_32x32 {
            get {
                object obj = ResourceManager.GetObject("SIDNotFound_32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Store_16x16 {
            get {
                object obj = ResourceManager.GetObject("Store_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Store_32x32 {
            get {
                object obj = ResourceManager.GetObject("Store_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon StoreApplicationGroup_16x16 {
            get {
                object obj = ResourceManager.GetObject("StoreApplicationGroup_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StoreApplicationGroup_32x32 {
            get {
                object obj = ResourceManager.GetObject("StoreApplicationGroup_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Task_16x16 {
            get {
                object obj = ResourceManager.GetObject("Task_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Task_32x32 {
            get {
                object obj = ResourceManager.GetObject("Task_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon WindowsBasicGroup_16x16 {
            get {
                object obj = ResourceManager.GetObject("WindowsBasicGroup_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon WindowsBasicGroup_32x32 {
            get {
                object obj = ResourceManager.GetObject("WindowsBasicGroup_32x32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon WindowsQueryLDAPGroup_16x16 {
            get {
                object obj = ResourceManager.GetObject("WindowsQueryLDAPGroup_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WindowsQueryLDAPGroup_32x32 {
            get {
                object obj = ResourceManager.GetObject("WindowsQueryLDAPGroup_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon WindowsUser_16x16 {
            get {
                object obj = ResourceManager.GetObject("WindowsUser_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WindowsUser_32x32 {
            get {
                object obj = ResourceManager.GetObject("WindowsUser_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
